# -*- coding: utf-8 -*-
"""method-1,2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGRsRnvsyLb8Lwy_On7lhoGSnF8EfvSX
"""

# ================================================================
# ENTANGLEMENT VERIFICATION — Bell Fidelity & Witness
# Final version — hardcoded source baseline, all fixes applied
# ================================================================

import zipfile, io, re, os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import csv

ZIP_FILE = "8207772.zip"

# ── 1. LOAD ALL FILES ──────────────────────────────────────────
with zipfile.ZipFile(ZIP_FILE, 'r') as outer:
    inner_bytes = outer.read("submission_datacode_upload.zip")

with zipfile.ZipFile(io.BytesIO(inner_bytes)) as inner:
    file_cache = {}
    for name in inner.namelist():
        if '__MACOSX' not in name and not os.path.basename(name).startswith('._'):
            file_cache[name] = inner.read(name)

print(f"Loaded {len(file_cache)} files.\n")

# ── 2. LOAD CALIBRATION: vpos → measured dt_ps ─────────────────
def load_vpos_to_dt(cache, fiber_key):
    key = next((k for k in cache
                if 'delays_and_vpos_dict' in k.lower()
                and fiber_key.lower() in k.lower()
                and '__macosx' not in k.lower()), None)
    if key is None:
        print(f"WARNING: calibration file not found for {fiber_key}")
        return {}
    text = cache[key].decode('utf-8', errors='replace')
    mapping = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#') or line.startswith('channel'):
            continue
        parts = line.split()
        try:
            vpos = int(parts[0].replace('vpos_', ''))
            dt   = float(parts[-1])
            mapping[vpos] = dt
        except (ValueError, IndexError):
            pass
    return mapping

hcf_vpos_to_dt = load_vpos_to_dt(file_cache, 'HCF')
smf_vpos_to_dt = load_vpos_to_dt(file_cache, 'SMF28')

print(f"HCF calibration : {len(hcf_vpos_to_dt)} vpos entries")
print(f"SMF calibration : {len(smf_vpos_to_dt)} vpos entries")

# ── 3. READ AUTHORS' PRE-COMPUTED CONCURRENCE + PURITY ─────────
def read_precomputed(raw_bytes):
    text = raw_bytes.decode('utf-8', errors='replace')
    rows = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        vals = line.split()
        if len(vals) >= 5:
            try:
                rows.append([float(v) for v in vals[:5]])
            except ValueError:
                pass
    return np.array(rows)

hcf_precomp_key = next((k for k in file_cache if 'dt_con_pur' in k and 'HCF' in k), None)
smf_precomp_key = next((k for k in file_cache if 'dt_con_pur' in k and 'SMF' in k), None)

hcf_pre = read_precomputed(file_cache[hcf_precomp_key])
smf_pre = read_precomputed(file_cache[smf_precomp_key])

print(f"\nHCF pre-computed rows : {len(hcf_pre)}")
print(f"SMF pre-computed rows : {len(smf_pre)}")

# ── 4. SOURCE BASELINE — hardcoded from separate measurement ────
# File: 2qubit_Tomo_w126ns_t10s_coincidences_20221110_1649.txt
# E_ZZ=-0.9848  E_XX=-0.9566  E_YY=-0.9621
# F = 0.25*(1 - E_XX - E_YY - E_ZZ) = 0.9759
F_src     = 0.9759
F_src_std = 0.0003
print(f"\nSOURCE (no fiber, separate measurement — hardcoded):")
print(f"  F = {F_src:.4f} ± {F_src_std:.4f}   W = {0.5-F_src:.4f}   *** ENTANGLED ***")

# ── 5. PARSE COINCIDENCE FILES ─────────────────────────────────
def parse_coinc(raw_bytes):
    text = raw_bytes.decode('utf-8', errors='replace')
    result = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        cols = line.split('\t')
        if len(cols) < 6:
            continue
        try:
            label = cols[0].strip().upper() + cols[1].strip().upper()
            result[label] = {
                'hs_hi': float(cols[2]),
                'hs_vi': float(cols[3]),
                'vs_hi': float(cols[4]),
                'vs_vi': float(cols[5]),
            }
        except (ValueError, IndexError):
            pass
    return result

# ── 6. CORRELATOR + BELL FIDELITY + WITNESS ────────────────────
# E(a,b) = (hs_hi + vs_vi - hs_vi - vs_hi) / N
# F(|Ψ⁻⟩) = (1/4)(1 - E_XX - E_YY - E_ZZ)
# W = 0.5 - F  →  W < 0 proves entanglement
def correlator(counts):
    N = counts['hs_hi'] + counts['hs_vi'] + counts['vs_hi'] + counts['vs_vi']
    if N < 1:
        return np.nan
    return (counts['hs_hi'] + counts['vs_vi'] - counts['hs_vi'] - counts['vs_hi']) / N

def bell_fidelity(d):
    for key in ['HH', 'DD', 'RR']:
        if key not in d:
            return np.nan, np.nan, np.nan, np.nan
    E_ZZ = correlator(d['HH'])
    E_XX = correlator(d['DD'])
    E_YY = correlator(d['RR'])
    if any(np.isnan(v) for v in [E_ZZ, E_XX, E_YY]):
        return np.nan, E_ZZ, E_XX, E_YY
    return 0.25 * (1.0 - E_XX - E_YY - E_ZZ), E_ZZ, E_XX, E_YY

# ── 7. MULTINOMIAL BOOTSTRAP ───────────────────────────────────
# n_boot=200: consistent with Methods 3 and 4
def bootstrap_F(d, n_boot=200):
    boot = []
    for _ in range(n_boot):
        rd = {}
        for label, counts in d.items():
            arr = np.array([counts['hs_hi'], counts['hs_vi'],
                            counts['vs_hi'], counts['vs_vi']])
            N = arr.sum()
            if N < 1:
                continue
            sampled = np.random.multinomial(int(N), arr / N).astype(float)
            rd[label] = {
                'hs_hi': sampled[0], 'hs_vi': sampled[1],
                'vs_hi': sampled[2], 'vs_vi': sampled[3]
            }
        F, *_ = bell_fidelity(rd)
        if not np.isnan(F):
            boot.append(F)
    if len(boot) < 10:
        return np.nan, np.nan
    return float(np.mean(boot)), float(np.std(boot))

# ── 8. FIND COINCIDENCE FILES ──────────────────────────────────
def find_all_coinc(cache, fiber_tag):
    out = []
    for p in cache:
        pl = p.lower()
        if (fiber_tag.lower() in pl
                and pl.endswith('coincidences.txt')
                and 'singles' not in pl):
            out.append(p)
    out.sort(key=lambda p: int(re.search(r'vpos_(\d+)', p).group(1))
             if re.search(r'vpos_(\d+)', p) else 0)
    return out

hcf_paths = find_all_coinc(file_cache, 'hcf_sigma_3')
smf_paths = find_all_coinc(file_cache, 'smf_sigma_3')

print(f"\nHCF files   : {len(hcf_paths)}")
print(f"SMF28 files : {len(smf_paths)}")

# ── 9. COMPUTE FIDELITY + WITNESS FOR ALL FILES ─────────────────
np.random.seed(42)
print("\n" + "="*70)
print("  BELL FIDELITY F  &  ENTANGLEMENT WITNESS W = 0.5 - F")
print("  F > 0.5  =>  entangled (point est.)  |  W < 0  =>  entangled")
print("  Threshold: (F_mean - 2*F_std) > 0.5  [2-sigma, consistent w/ Methods 3 & 4]")
print("  Bootstrap: multinomial n_boot=200  (consistent with Methods 3 & 4)")
print("="*70)

def process_files(paths, fiber_label, vpos_to_dt):
    results = []
    skipped = 0
    print(f"\n{fiber_label}:")
    for path in paths:
        m = re.search(r'vpos_(\d+)', path)
        if not m:
            skipped += 1
            continue
        vpos = int(m.group(1))
        dt = vpos_to_dt.get(vpos, None)
        if dt is None:
            skipped += 1
            continue
        d = parse_coinc(file_cache[path])
        F, E_ZZ, E_XX, E_YY = bell_fidelity(d)
        if np.isnan(F):
            skipped += 1
            continue

        F_mean, F_std = bootstrap_F(d, n_boot=200)
        W      = 0.5 - F_mean          # witness from bootstrap mean
        W_std  = F_std                  # σ_W = σ_F (0.5 is constant)

        # ── FIX: 2-sigma lower bound criterion (consistent with Methods 3 & 4)
        entangled_2sig = (F_mean - 2.0 * F_std) > 0.5

        results.append({
            'vpos': vpos, 'dt_ps': dt,
            'F': F_mean, 'F_std': F_std,
            'W': W, 'W_std': W_std,
            'entangled_2sig': entangled_2sig,
            'E_ZZ': E_ZZ, 'E_XX': E_XX, 'E_YY': E_YY
        })

        status = 'ENTANGLED (2-sigma)' if entangled_2sig else 'not confirmed'
        print(f"  dt={dt:>7.2f}ps (vpos={vpos:>3})  "
              f"F={F_mean:.4f}+/-{F_std:.4f}  W={W:.4f}  {status}")

    if skipped:
        print(f"  [{skipped} files skipped: not valid coincidence data]")
    results.sort(key=lambda r: r['dt_ps'])
    return results

hcf_res = process_files(hcf_paths, "HCF (NANF fiber)", hcf_vpos_to_dt)
smf_res = process_files(smf_paths, "SMF28 fiber",       smf_vpos_to_dt)

# ── 10. PLOT ───────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

dt_h = [r['dt_ps'] for r in hcf_res]
dt_s = [r['dt_ps'] for r in smf_res]
all_dt = dt_h + dt_s + list(hcf_pre[:,0]) + list(smf_pre[:,0])
xmin, xmax = 30, max(all_dt) + 15   # FIX: xmin=30 (not 0) — avoids empty left margin

HCF_COLOR = '#1a78c2'
SMF_COLOR = '#e05c2a'
NOTE_TXT  = ('Note: coincidence scan starts at Δt≈38 ps (HCF), Δt≈78 ps (SMF28)\n'
             "Authors\' data (top panels) from finer independent scan")

# Panel 1 — Authors' Concurrence
ax = axes[0][0]
ax.errorbar(hcf_pre[:,0], hcf_pre[:,1], yerr=hcf_pre[:,3],
            fmt='o-', color=HCF_COLOR, lw=2, ms=5, capsize=3, label='NANF (HCF)')
ax.errorbar(smf_pre[:,0], smf_pre[:,1], yerr=smf_pre[:,3],
            fmt='s--', color=SMF_COLOR, lw=2, ms=5, capsize=3, label='SMF28')
ax.axhline(0, color='black', ls='--', lw=1)
ax.set_xlabel('Time-bin spacing Δt (ps)')
ax.set_ylabel('Concurrence C')
ax.set_title("Authors\' Concurrence (paper Fig. 4a)")
ax.set_xlim(xmin, xmax)
ax.legend(); ax.grid(alpha=0.3)

# Panel 2 — Authors' Purity
ax = axes[0][1]
ax.errorbar(hcf_pre[:,0], hcf_pre[:,2], yerr=hcf_pre[:,4],
            fmt='o-', color=HCF_COLOR, lw=2, ms=5, capsize=3, label='NANF (HCF)')
ax.errorbar(smf_pre[:,0], smf_pre[:,2], yerr=smf_pre[:,4],
            fmt='s--', color=SMF_COLOR, lw=2, ms=5, capsize=3, label='SMF28')
ax.set_xlabel('Time-bin spacing Δt (ps)')
ax.set_ylabel('Purity γ = Tr(ρ²)')
ax.set_title("Authors\' Purity (paper Fig. 4a)")
ax.set_xlim(xmin, xmax)
ax.legend(); ax.grid(alpha=0.3)

# Panel 3 — Our Bell Fidelity
ax = axes[1][0]
ax.errorbar(dt_h, [r['F'] for r in hcf_res],
            yerr=[r['F_std'] for r in hcf_res],
            fmt='o-', color=HCF_COLOR, lw=2, ms=5, capsize=3, label='NANF (HCF)')
ax.errorbar(dt_s, [r['F'] for r in smf_res],
            yerr=[r['F_std'] for r in smf_res],
            fmt='s--', color=SMF_COLOR, lw=2, ms=5, capsize=3, label='SMF28')
ax.axhline(F_src, color='green', ls=':', lw=2,
           label=f'Source baseline F={F_src:.3f}+/-{F_src_std:.4f}')
ax.axhline(0.5, color='black', ls='--', lw=1.5, label='Threshold F=0.5')
ax.fill_between([xmin, xmax], [0, 0], [0.5, 0.5],
                color='red', alpha=0.07, label='Not entangled')
ax.text(0.02, 0.04, NOTE_TXT,
        transform=ax.transAxes, fontsize=7, color='gray', va='bottom')
ax.set_xlabel('Time-bin spacing Δt (ps)')
ax.set_ylabel('Bell Fidelity F(|Ψ⁻⟩)')
ax.set_title('Our Bell Fidelity to |Ψ⁻⟩ — New Analysis')
ax.set_xlim(xmin, xmax)
ax.set_ylim(0.3, 1.05)
ax.legend(fontsize=8); ax.grid(alpha=0.3)

# Panel 4 — Our Entanglement Witness
ax = axes[1][1]
all_W     = [r['W'] for r in hcf_res + smf_res]
all_W_err = [r['W_std'] for r in hcf_res + smf_res]
w_min = min(w - e for w, e in zip(all_W, all_W_err)) - 0.03
w_max = max(w + e for w, e in zip(all_W, all_W_err)) + 0.05

ax.errorbar(dt_h, [r['W'] for r in hcf_res],
            yerr=[r['W_std'] for r in hcf_res],
            fmt='o-', color=HCF_COLOR, lw=2, ms=5, capsize=3, label='NANF (HCF)')
ax.errorbar(dt_s, [r['W'] for r in smf_res],
            yerr=[r['W_std'] for r in smf_res],
            fmt='s--', color=SMF_COLOR, lw=2, ms=5, capsize=3, label='SMF28')
ax.axhline(0.5 - F_src, color='green', ls=':', lw=2,
           label=f'Source baseline W={0.5-F_src:.3f}')
ax.axhline(0, color='black', ls='--', lw=1.5, label='W=0 threshold')
ax.fill_between([xmin, xmax], [w_min, w_min], [0, 0],
                color='blue', alpha=0.08, label='W<0: entangled')
ax.fill_between([xmin, xmax], [0, 0], [w_max, w_max],
                color='red', alpha=0.08, label='W>0: not confirmed')
ax.text(0.02, 0.97, NOTE_TXT,
        transform=ax.transAxes, fontsize=7, color='gray', va='top')
ax.set_xlabel('Time-bin spacing Δt (ps)')
ax.set_ylabel('Witness W = 0.5 − F')
ax.set_title('Our Entanglement Witness — New Analysis')
ax.set_xlim(xmin, xmax)
ax.set_ylim(w_min, w_max)
ax.legend(fontsize=8); ax.grid(alpha=0.3)

plt.suptitle(
    'Entanglement Verification — NANF vs SMF28\n'
    "Top: Authors\' concurrence & purity  |  Bottom: Our Bell fidelity & witness",
    fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('entanglement_verification.png', dpi=150, bbox_inches='tight')
plt.close()
print("\nPlot saved: entanglement_verification.png")

# ── 11. SAVE CSV ───────────────────────────────────────────────
with open('fidelity_witness_results.csv', 'w', newline='') as f:
    w = csv.writer(f)
    # FIX: added 'entangled_2sig' column (2-sigma lower bound criterion)
    w.writerow(['dt_ps', 'vpos', 'fiber',
                'F_mean', 'F_std', 'W', 'W_std',
                'entangled_2sig',
                'E_ZZ', 'E_XX', 'E_YY'])
    for r in hcf_res:
        w.writerow([round(r['dt_ps'],2), r['vpos'], 'HCF',
                    round(r['F'],6), round(r['F_std'],6),
                    round(r['W'],6), round(r['W_std'],6),
                    r['entangled_2sig'],
                    round(r['E_ZZ'],6), round(r['E_XX'],6), round(r['E_YY'],6)])
    for r in smf_res:
        w.writerow([round(r['dt_ps'],2), r['vpos'], 'SMF28',
                    round(r['F'],6), round(r['F_std'],6),
                    round(r['W'],6), round(r['W_std'],6),
                    r['entangled_2sig'],
                    round(r['E_ZZ'],6), round(r['E_XX'],6), round(r['E_YY'],6)])

print("CSV  saved: fidelity_witness_results.csv")
print("\n" + "="*70)
print("  DONE — paste full output for verification")
print("="*70)

