# -*- coding: utf-8 -*-
"""method-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r3l_iCXISqRskubH0ljBlRsoTni1UwFc
"""

import zipfile, io, re, os
import numpy as np
from scipy.optimize import minimize
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import csv

ZIP_FILE = "8207772.zip"

# ── 1. LOAD FILES ──────────────────────────────────────────────
with zipfile.ZipFile(ZIP_FILE, 'r') as outer:
    inner_bytes = outer.read("submission_datacode_upload.zip")

with zipfile.ZipFile(io.BytesIO(inner_bytes)) as inner:
    file_cache = {}
    for name in inner.namelist():
        if '__MACOSX' not in name and not os.path.basename(name).startswith('._'):
            file_cache[name] = inner.read(name)

print(f"Loaded {len(file_cache)} files.")

# ── 2. CALIBRATION: vpos -> real dt (picoseconds) ─────────────
def load_vpos_to_dt(cache, fiber_key):
    key = next((k for k in cache
                if 'delays_and_vpos_dict' in k.lower()
                and fiber_key.lower() in k.lower()
                and '__macosx' not in k.lower()), None)
    if key is None:
        print(f"WARNING: calibration file not found for {fiber_key}")
        return {}
    text = cache[key].decode('utf-8', errors='replace')
    mapping = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#') or line.startswith('channel'):
            continue
        parts = line.split()
        try:
            mapping[int(parts[0].replace('vpos_', ''))] = float(parts[-1])
        except (ValueError, IndexError):
            pass
    return mapping

hcf_vpos_to_dt = load_vpos_to_dt(file_cache, 'HCF')
smf_vpos_to_dt = load_vpos_to_dt(file_cache, 'SMF28')
print(f"HCF calibration : {len(hcf_vpos_to_dt)} vpos entries")
print(f"SMF calibration : {len(smf_vpos_to_dt)} vpos entries")

# ── 3. SOURCE BASELINE — Werner inference from measured F ──────
# Source not in this zip. Verified earlier: F_src = 0.9759 +/- 0.0003
# Werner state: rho = p|Psi->< Psi-| + (1-p) I/4
#   F = (3p+1)/4  =>  p = (4F-1)/3
#   T_matrix = -p * I_3  =>  M = p^2 I_3
#   S_max = 2*sqrt(2p^2) = 2*sqrt(2)*p = (2*sqrt(2)/3)*(4F-1)
F_src     = 0.9759
F_src_std = 0.0003
S_src     = 2.0 * np.sqrt(2) * (4.0 * F_src - 1.0) / 3.0       # = 2.7382
S_src_std = 2.0 * np.sqrt(2) * 4.0 * F_src_std / 3.0            # propagated
print(f"\nSOURCE baseline (Werner inference from F_src={F_src}):")
print(f"  S_src = (2*sqrt(2)/3) * (4*{F_src} - 1) = {S_src:.4f} +/- {S_src_std:.4f}")

# ── 4. COINCIDENCE PARSER ──────────────────────────────────────
# Tab-separated: s_base [TAB] i_base [TAB] N_ss [TAB] N_si [TAB] N_is [TAB] N_ii
def parse_coinc(raw_bytes):
    text = raw_bytes.decode('utf-8', errors='replace')
    result = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        cols = line.split('	')
        if len(cols) < 6:
            continue
        try:
            label = cols[0].strip().upper() + cols[1].strip().upper()
            result[label] = np.array([float(cols[2]), float(cols[3]),
                                      float(cols[4]), float(cols[5])])
        except (ValueError, IndexError):
            pass
    return result

# ── 5. PROJECTORS ──────────────────────────────────────────────
sq2 = 1.0 / np.sqrt(2)
STATES = {
    'H': np.array([1,        0       ], dtype=complex),
    'V': np.array([0,        1       ], dtype=complex),
    'D': np.array([sq2,      sq2     ], dtype=complex),
    'A': np.array([sq2,     -sq2     ], dtype=complex),
    'R': np.array([sq2,   sq2*1j    ], dtype=complex),
    'L': np.array([sq2,  -sq2*1j    ], dtype=complex),
}
BASIS_EIGENSTATES = {
    'H': ('H', 'V'),
    'D': ('D', 'A'),
    'R': ('R', 'L'),
}

def projector(s):
    v = STATES[s]
    return np.outer(v, v.conj())

def get_projectors(label):
    sp, sm = BASIS_EIGENSTATES[label[0]]
    ip, im = BASIS_EIGENSTATES[label[1]]
    return [
        np.kron(projector(sp), projector(ip)),
        np.kron(projector(sp), projector(im)),
        np.kron(projector(sm), projector(ip)),
        np.kron(projector(sm), projector(im)),
    ]

ALL_PROJECTORS = {
    lbl: get_projectors(lbl)
    for lbl in ['HH', 'HD', 'HR', 'DH', 'DD', 'DR', 'RH', 'RD', 'RR']
}

# ── 6. MLE DENSITY MATRIX — Cholesky parametrization ───────────
# rho = T_dag @ T / Tr(T_dag @ T),  T lower-triangular
# Guarantees: Hermitian, positive semidefinite, Tr(rho)=1
# 16 real params: 4 diagonal (real) + 6 complex off-diagonal (2 each)

def params_to_rho(params):
    T = np.zeros((4, 4), dtype=complex)
    idx = 0
    for i in range(4):
        T[i, i] = params[idx]
        idx += 1
    for i in range(1, 4):
        for j in range(i):
            T[i, j] = params[idx] + 1j * params[idx + 1]
            idx += 2
    rho = T.conj().T @ T
    tr = np.trace(rho)
    if abs(tr) < 1e-12:
        return np.eye(4, dtype=complex) / 4.0
    return rho / tr

def neg_log_likelihood(params, coinc_dict):
    rho = params_to_rho(params)
    nll = 0.0
    for label, projs in ALL_PROJECTORS.items():
        if label not in coinc_dict:
            continue
        counts = coinc_dict[label]
        if counts.sum() < 1:
            continue
        for k in range(4):
            p_k = max(1e-10, float(np.real(np.trace(rho @ projs[k]))))
            if counts[k] > 0:
                nll -= counts[k] * np.log(p_k)
    return nll

def is_physical(rho, atol_tr=1e-3, atol_eig=1e-4):
    tr   = float(np.real(np.trace(rho)))
    eigs = np.linalg.eigvalsh(rho)
    return np.isclose(tr, 1.0, atol=atol_tr) and np.all(eigs >= -atol_eig)

def mle_reconstruct(coinc_dict):
    """
    Returns physical rho (4x4 complex) or None if all attempts fail.
    Attempt 0: identity-based x0.
    Attempts 1-3: random x0 via local RNG (does NOT touch global seed).
    """
    available = [k for k in ALL_PROJECTORS
                 if k in coinc_dict and coinc_dict[k].sum() > 0]
    if len(available) < 9:
        return None

    def run_opt(x0):
        return minimize(neg_log_likelihood, x0,
                        args=(coinc_dict,),
                        method='L-BFGS-B',
                        options={'maxiter': 5000, 'ftol': 1e-12, 'gtol': 1e-8})

    # Attempt 0
    x0 = np.zeros(16)
    x0[0] = x0[4] = x0[9] = x0[15] = 0.5
    res = run_opt(x0)
    rho = params_to_rho(res.x)
    if res.success and is_physical(rho):
        return rho

    # Attempts 1-3: local RNG, reproducible, does NOT disturb global np state
    for attempt in range(3):
        rng = np.random.default_rng(attempt * 7 + 13)
        x0r = rng.normal(0, 0.3, 16)
        for di in [0, 4, 9, 15]:
            x0r[di] = abs(x0r[di]) + 0.1
        res2 = run_opt(x0r)
        rho2 = params_to_rho(res2.x)
        if is_physical(rho2):
            print(f"    INFO: MLE converged on retry {attempt + 1}")
            return rho2

    print("    ERROR: MLE failed all retries — point SKIPPED")
    return None

# ── 7. PURITY ──────────────────────────────────────────────────
def purity(rho):
    return float(np.real(np.trace(rho @ rho)))

# ── 8. T-MATRIX AND HORODECKI S_max ────────────────────────────
sx = np.array([[0,   1 ], [1,   0 ]], dtype=complex)
sy = np.array([[0, -1j], [1j,  0 ]], dtype=complex)
sz = np.array([[1,   0 ], [0,  -1 ]], dtype=complex)
PAULIS = [sx, sy, sz]

def compute_T_matrix(rho):
    T = np.zeros((3, 3), dtype=float)
    for i, si in enumerate(PAULIS):
        for j, sj in enumerate(PAULIS):
            T[i, j] = float(np.real(np.trace(rho @ np.kron(si, sj))))
    return T

def horodecki_smax(rho):
    """
    Horodecki (1995): S_max = 2 * sqrt(M1 + M2)
    M = T.T @ T,   M1 >= M2 = two largest eigenvalues of M
    """
    T    = compute_T_matrix(rho)
    M    = T.T @ T
    eigs = np.sort(np.linalg.eigvalsh(M))[::-1]
    return 2.0 * np.sqrt(eigs[0] + eigs[1]), eigs[0], eigs[1]

# ── 9. BOOTSTRAP — multinomial resampling ──────────────────────
# NO seed inside this function.
# The single np.random.seed(42) at the top of the script governs everything.
# Each bootstrap call uses the next segment of the deterministic stream.
# This is fully reproducible AND each file gets different bootstrap samples.

def bootstrap_smax(coinc_dict, n_boot=200):
    S_boot = []
    n_failed = 0
    for _ in range(n_boot):
        resampled = {}
        for label, counts in coinc_dict.items():
            N_float = counts.sum()          # keep as float — no int() truncation
            if N_float < 1:
                continue
            p = counts / N_float            # normalized probability vector
            resampled[label] = np.random.multinomial(
                int(round(N_float)), p      # round before int, not truncate
            ).astype(float)
        rho_b = mle_reconstruct(resampled)
        if rho_b is None:
            n_failed += 1
            continue
        S_b, _, _ = horodecki_smax(rho_b)
        if not np.isnan(S_b):
            S_boot.append(S_b)
    if n_failed > n_boot * 0.3:
        print(f"    WARNING: {n_failed}/{n_boot} bootstrap resamples failed MLE")
    if len(S_boot) < 10:
        return np.nan, np.nan
    return float(np.mean(S_boot)), float(np.std(S_boot))

# ── 10. FILE FINDER ────────────────────────────────────────────
def find_all_coinc(cache, fiber_tag):
    out = []
    for p in cache:
        pl = p.lower()
        if (fiber_tag.lower() in pl
                and pl.endswith('coincidences.txt')
                and 'singles' not in pl):
            out.append(p)
    out.sort(key=lambda p: int(re.search(r'vpos_(\d+)', p).group(1))
             if re.search(r'vpos_(\d+)', p) else 0)
    return out

hcf_paths = find_all_coinc(file_cache, 'hcf_sigma_3')
smf_paths = find_all_coinc(file_cache, 'smf_sigma_3')
print(f"\nHCF files   : {len(hcf_paths)}")
print(f"SMF28 files : {len(smf_paths)}")

# ── 11. MAIN ANALYSIS LOOP ─────────────────────────────────────
np.random.seed(42)    # single global seed — reproducible, each file gets unique stream
S_CLASSICAL = 2.0
S_TSIRELSON = 2.0 * np.sqrt(2)

print("\n" + "="*72)
print("  METHOD 3: CHSH S_max via Horodecki (1995)")
print(f"  S > {S_CLASSICAL:.1f}           -> NONLOCAL -> entanglement proven")
print(f"  S = {S_TSIRELSON:.4f}  -> Tsirelson bound (perfect Bell state)")
print("  Threshold : (S_mean - 2*S_std) > 2.0  [2-sigma conservative]")
print("  Estimator : S_mean +/- S_std from multinomial bootstrap (n=200)")
print("="*72)

def process_chsh(paths, fiber_label, vpos_to_dt, n_boot=200):
    results = []
    skipped = 0
    print(f"\n{fiber_label}:")
    for path in paths:
        m = re.search(r'vpos_(\d+)', path)
        if not m:
            skipped += 1
            continue
        vpos = int(m.group(1))
        dt   = vpos_to_dt.get(vpos, None)
        if dt is None:
            skipped += 1
            continue

        coinc = parse_coinc(file_cache[path])
        rho   = mle_reconstruct(coinc)
        if rho is None:
            skipped += 1
            continue

        pur              = purity(rho)
        S_mle, m1, m2   = horodecki_smax(rho)
        S_mean, S_std    = bootstrap_smax(coinc, n_boot=n_boot)

        if np.isnan(S_mean):
            skipped += 1
            continue

        entangled    = (S_mean - 2.0 * S_std) > S_CLASSICAL
        significance = (S_mean - S_CLASSICAL) / S_std if S_std > 0 else float('inf')

        pur_str = ('pure'       if pur > 0.95
                   else 'mixed' if pur < 0.50
                   else 'part.mixed')
        status  = 'NONLOCAL -> ENTANGLED' if entangled else 'not confirmed'

        results.append({
            'vpos': vpos, 'dt_ps': dt,
            'S_mle': S_mle, 'S_mean': S_mean, 'S_std': S_std,
            'purity': pur, 'entangled': entangled,
            'significance': significance,
            'm1': m1, 'm2': m2
        })

        print(f"  dt={dt:>7.2f}ps  "
              f"S={S_mean:.4f}+/-{S_std:.4f}  "
              f"sig={significance:+.1f}s  "
              f"pur={pur:.3f}({pur_str})  "
              f"{status}")

    if skipped:
        print(f"  [{skipped} points skipped]")
    results.sort(key=lambda r: r['dt_ps'])
    return results

hcf_res = process_chsh(hcf_paths, "HCF (NANF fiber)", hcf_vpos_to_dt, n_boot=200)
smf_res = process_chsh(smf_paths, "SMF28 fiber",       smf_vpos_to_dt, n_boot=200)

# ── 12. PLOT ───────────────────────────────────────────────────
HCF_COLOR = '#1a78c2'
SMF_COLOR = '#e05c2a'

dt_h = [r['dt_ps'] for r in hcf_res]
dt_s = [r['dt_ps'] for r in smf_res]
xmin = 0
xmax = max(dt_h + dt_s) + 15

fig, ax = plt.subplots(figsize=(11, 6))

if hcf_res:
    ax.errorbar(dt_h,
                [r['S_mean'] for r in hcf_res],
                yerr=[r['S_std'] for r in hcf_res],
                fmt='o-', color=HCF_COLOR, lw=2, ms=6, capsize=4,
                label='NANF (HCF)')

if smf_res:
    ax.errorbar(dt_s,
                [r['S_mean'] for r in smf_res],
                yerr=[r['S_std'] for r in smf_res],
                fmt='s--', color=SMF_COLOR, lw=2, ms=6, capsize=4,
                label='SMF28')

ax.axhline(S_src, color='green', ls=':', lw=2,
           label=f'Source (Werner from F): S = {S_src:.4f}')
ax.axhline(S_CLASSICAL, color='black', ls='--', lw=2,
           label='Classical bound S=2')
ax.axhline(S_TSIRELSON, color='purple', ls=':', lw=1.5,
           label=f'Tsirelson S=2*sqrt(2)={S_TSIRELSON:.3f}')

ax.fill_between([xmin, xmax], [0, 0], [S_CLASSICAL, S_CLASSICAL],
                color='red', alpha=0.07, label='S<=2: classical region')
ax.fill_between([xmin, xmax], [S_CLASSICAL, S_CLASSICAL],
                [S_TSIRELSON + 0.1, S_TSIRELSON + 0.1],
                color='blue', alpha=0.05, label='S>2: nonlocal (entangled)')

note = ('Source S: Werner inference S = (2*sqrt(2)/3)*(4F-1), F=0.9759\n'
        'Derived from: rho_W = p|Psi->< Psi-| + (1-p)I/4 with p=(4F-1)/3\n'
        'Error bars = multinomial bootstrap std (n=200)\n'
        'Threshold: S_mean - 2*S_std > 2.0  [2-sigma]')
ax.text(0.02, 0.04, note, transform=ax.transAxes,
        fontsize=7.5, color='gray', va='bottom')

ax.set_xlabel('Time-bin spacing dt (ps)', fontsize=12)
ax.set_ylabel('S_max  (Horodecki 1995)', fontsize=12)
ax.set_title('CHSH S_max via Horodecki (1995) — NANF vs SMF28\n'
             'S_max > 2 proves nonlocality (sufficient for entanglement)',
             fontsize=12, fontweight='bold')
ax.set_xlim(xmin, xmax)
ax.set_ylim(1.3, S_TSIRELSON + 0.15)
ax.legend(fontsize=9, loc='lower right')
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('chsh_smax_horodecki.png', dpi=150, bbox_inches='tight')
plt.close()
print("\nPlot saved: chsh_smax_horodecki.png")

# ── 13. CSV ────────────────────────────────────────────────────
with open('chsh_horodecki_results.csv', 'w', newline='') as f:
    w = csv.writer(f)
    w.writerow(['dt_ps', 'vpos', 'fiber',
                'S_mle', 'S_mean', 'S_std',
                'significance_sigma', 'entangled_2sigma',
                'purity', 'm1', 'm2'])
    for r in hcf_res:
        sig = (r['S_mean'] - 2.0) / r['S_std'] if r['S_std'] > 0 else float('inf')
        w.writerow([round(r['dt_ps'], 2), r['vpos'], 'HCF',
                    round(r['S_mle'], 6), round(r['S_mean'], 6), round(r['S_std'], 6),
                    round(sig, 4), r['entangled'],
                    round(r['purity'], 6), round(r['m1'], 6), round(r['m2'], 6)])
    for r in smf_res:
        sig = (r['S_mean'] - 2.0) / r['S_std'] if r['S_std'] > 0 else float('inf')
        w.writerow([round(r['dt_ps'], 2), r['vpos'], 'SMF28',
                    round(r['S_mle'], 6), round(r['S_mean'], 6), round(r['S_std'], 6),
                    round(sig, 4), r['entangled'],
                    round(r['purity'], 6), round(r['m1'], 6), round(r['m2'], 6)])

print("CSV  saved: chsh_horodecki_results.csv")
print("\n" + "="*72)
print("  DONE — paste full output for verification")
print("="*72)

